language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
deploy:
  provider: releases
  api_key:
    secure: UME5r6KD7+BiScvqBawj1PZ+49ougYAa03DHIR7OwQVc3dxj4tg6im59n7XkfTqL6aSsskEE12wZ78wm7nbZArk65fpc2KULnffC2LaBgTU9FRVdN+kSjfO+SPnREGwWTsR3QD6zumuMFbL6yHSXrCwhIyq2Dn0TvKeFXKP3G1BYPgU5DCjGX5LDxaOkO8d4RTTcNEzg/GLAynxCq1iIIN1ycpmo86nXfN4HsDoXUJiB5F+9sdLtURfxvG480DGbRRCxNj/KAveun65s9dWAWge6YyNsaTGMuJrGu/Jjf0e69eokmxnnYQ0uFJ+jY1w+nQzQlMAuYq1bZB9iVNHngiky0JuTwrDV9NtFfSGviXLIjnq5pkNAPOGZcXpRcv097jRPOf+EF8O2gluMfdzw0M6h5gy52cfOwsmqdHZvCHF1ZJx5RwXHOTO4tGDlhjAmipKtALEKxYhwKRkYTjaWTu4JSLk9jVDAhlJf9yL5Ka2zzDzdMENfDCLHqKC00Wm/YQ+JU1/ff+VdCeyem0j0y7em9tA2eLyiGCtZZloqw73pDLokIix6v1KVb1/kvz/yqOVNZxfZnEPHQbQU0e8fCOQFp9JGJNB9MW9YeLqFzq7ZUazl3zSC+l8veJidfhkQBZTPfVZjtCQWFkgQynlLzKWUQa9BUU4SX6wn5lIgEes=
  file: app/build/outputs/apk/release/app-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
